# Generated by Django 4.2.9 on 2024-03-19 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(default='missing username', max_length=64)),
                ('display_name', models.CharField(default='missing display name', max_length=64)),
                ('user_type', models.CharField(default='', max_length=32)),
                ('broadcaster_type', models.CharField(default='', max_length=32)),
                ('description', models.TextField(default='')),
                ('profile_image_url', models.TextField(default='missing profile image url')),
                ('offline_image_url', models.TextField(default='missing offline image url')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default='missing message id', max_length=64)),
                ('content_offset', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='created at')),
                ('message', models.TextField(default='')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.chatter')),
            ],
        ),
    ]
