# Generated by Django 4.2.9 on 2024-03-21 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0002_remove_chatmessage_id_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='chatter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('url', models.TextField(default='missing clip url')),
                ('embed_url', models.TextField(default='missing embed url')),
                ('broadcaster_id', models.IntegerField(default=-1)),
                ('broadcaster_name', models.CharField(default='missing broadcaster name', max_length=64)),
                ('video_id', models.CharField(default='', max_length=32)),
                ('game_id', models.CharField(default='missing game id', max_length=32)),
                ('language', models.CharField(default='en', max_length=64)),
                ('title', models.CharField(default='missing clip title', max_length=128)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc), verbose_name='created at')),
                ('thumbnail_url', models.TextField(default='missing thumbnail url')),
                ('duration', models.FloatField(default=0.0)),
                ('vod_offset', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.chatter')),
            ],
        ),
    ]
