# Generated by Django 4.2.9 on 2024-03-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0003_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='commentor',
            new_name='commenter',
        ),
    ]
