# Generated by Django 4.2.9 on 2024-03-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0005_rename_chatter_twitchuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='clip_id',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
