# Generated by Django 4.2.9 on 2024-03-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0006_alter_clip_clip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='title',
            field=models.TextField(default='missing clip title'),
        ),
    ]
