# Generated by Django 4.2.9 on 2024-03-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0008_alter_chatmessage_message_id_alter_clip_clip_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('month', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0)),
                ('clip_count', models.IntegerField(default=0)),
                ('clip_views', models.IntegerField(default=0)),
                ('monthly_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.monthlyrecap')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itswill_org.twitchuser')),
            ],
            options={
                'unique_together': {('monthly_recap', 'twitch_user')},
            },
        ),
    ]
