# Generated by Django 4.2.9 on 2024-03-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0010_monthlyrecap_total_clip_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrecap',
            name='total_chatters',
            field=models.IntegerField(default=0),
        ),
    ]
