# Generated by Django 4.2.9 on 2024-03-23 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0012_video_monthlyrecap_total_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('image_filename', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('killcount_known', models.BooleanField(default=True)),
                ('killcount', models.IntegerField(default=0)),
                ('kill_term', models.CharField(default='KC', max_length=255)),
                ('date_known', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('clip_url', models.CharField(default='', max_length=512)),
                ('tweet_url', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
