# Generated by Django 4.2.9 on 2024-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0013_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='clip_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tweet_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
