# Generated by Django 4.2.9 on 2024-03-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0014_alter_pet_clip_url_alter_pet_tweet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='kill_term_pluralize',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kill_term',
            field=models.CharField(default='killcount', max_length=255),
        ),
    ]
