# Generated by Django 4.2.9 on 2024-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0016_remove_pet_image_filename_pet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='secondary_kill_term',
            field=models.CharField(default='killcount', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_kill_term_pluralize',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_killcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='acquired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(blank=True, upload_to='petimg/'),
        ),
    ]
