# Generated by Django 4.2.9 on 2024-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0017_pet_secondary_kill_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='secondary_killcount_needed',
            field=models.BooleanField(default=False),
        ),
    ]
