# Generated by Django 4.2.9 on 2024-03-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0019_monthlyrecap_total_chicken_monthlyrecap_total_cum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyUserData',
            new_name='UserRecapData',
        ),
    ]
