# Generated by Django 4.2.9 on 2024-03-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0020_rename_monthlyuserdata_userrecapdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyRecap',
            new_name='OverallRecapData',
        ),
    ]
