# Generated by Django 4.2.9 on 2024-03-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0021_rename_monthlyrecap_overallrecapdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='monthly_recap',
            new_name='overall_recap',
        ),
        migrations.AlterUniqueTogether(
            name='userrecapdata',
            unique_together={('overall_recap', 'twitch_user')},
        ),
    ]
