# Generated by Django 4.2.9 on 2024-03-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0023_rename_total_chatters_overallrecapdata_count_chatters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='clip_count',
            new_name='count_clip_views',
        ),
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='clip_views',
            new_name='count_clips',
        ),
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='message_count',
            new_name='count_messages',
        ),
    ]
