# Generated by Django 4.2.9 on 2024-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0024_rename_clip_count_userrecapdata_count_clip_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
