# Generated by Django 4.2.9 on 2024-03-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0025_overallrecapdata_first_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='count_clip_views',
            new_name='count_clip_views_temp',
        ),
    ]
