# Generated by Django 4.2.9 on 2024-03-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0026_rename_count_clip_views_userrecapdata_count_clip_views_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecapdata',
            old_name='count_clips',
            new_name='count_clip_views',
        ),
    ]
