# Generated by Django 4.2.9 on 2024-03-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0028_rename_count_clip_views_temp_userrecapdata_count_clips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
