# Generated by Django 4.2.9 on 2024-04-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0031_copypastegroup_copypaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copypaste',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
