# Generated by Django 4.2.9 on 2024-04-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0032_alter_copypaste_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
