# Generated by Django 4.2.11 on 2024-06-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0033_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascii',
            name='is_garf',
            field=models.BooleanField(default=False),
        ),
    ]
