# Generated by Django 4.2.11 on 2024-08-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0034_ascii_is_garf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at',)},
        ),
    ]
