# Generated by Django 4.2.11 on 2024-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0035_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascii',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='copypastegroup',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
