# Generated by Django 5.2.5 on 2025-12-29 06:03

import django.db.models.deletion
import itswill_org.models
from django.db import migrations, models
import re

class StringCountField(itswill_org.models.StatField):
    match_list = []
    match_regex = None
    use_images = True

    def __init__(
        self, match_list=[], emote_list=None, use_images=True, *args, **kwargs
    ):
        self.match_list = match_list
        self.match_regex = re.compile(
            re.compile(
                rf"(?<![^\s_-]){'|'.join(self.match_list)}(?![^\s_-])", re.IGNORECASE
            )
        )
        self.emote_list = self.match_list if emote_list is None else emote_list
        self.use_images = use_images

        super().__init__(*args, **kwargs)

    @property
    def non_db_attrs(self):
        return super().non_db_attrs + (
            "match_list",
            "match_regex",
            "use_images",
            "show_recap",
        )

class Migration(migrations.Migration):

    replaces = [('itswill_org', '0036_alter_ascii_title_alter_copypastegroup_title'), ('itswill_org', '0037_alter_clip_options_alter_pet_options_and_more'), ('itswill_org', '0038_alter_overallrecapdata_count_chicken_and_more'), ('itswill_org', '0039_overallrecapdata_count_cinema_and_more'), ('itswill_org', '0040_overallrecapdata_count_goodboy_and_more'), ('itswill_org', '0041_overallrecapdata_count_chedda_and_more'), ('itswill_org', '0042_overallrecapdata_leaderboards'), ('itswill_org', '0043_alter_overallrecapdata_leaderboards'), ('itswill_org', '0044_alter_overallrecapdata_count_chatters_and_more'), ('itswill_org', '0045_pet_drop_rate_pet_drop_rate_known_and_more'), ('itswill_org', '0046_overallrecapdata_count_caw_and_more'), ('itswill_org', '0047_overallrecapdata_count_ascii_and_more'), ('itswill_org', '0048_twitchuser_is_bot'), ('itswill_org', '0049_overallrecapdata_last_message_and_more'), ('itswill_org', '0050_overallrecapdata_count_400_userrecapdata_count_400'), ('itswill_org', '0051_overallrecapdata_count_burger_and_more'), ('itswill_org', '0052_overallrecapdata_count_bork_userrecapdata_count_bork'), ('itswill_org', '0053_overallrecapdata_count_plus1_and_more'), ('itswill_org', '0054_overallrecapdata_count_clip_duration_and_more'), ('itswill_org', '0055_overallrecapdata_count_chatter_and_more'), ('itswill_org', '0056_rename_count_chatter_overallrecapdata_count_first_and_more'), ('itswill_org', '0057_overallrecapdata_count_at_bot_and_more'), ('itswill_org', '0058_overallrecapdata_count_yt_userrecapdata_count_yt'), ('itswill_org', '0059_overallrecapdata_count_q_userrecapdata_count_q'), ('itswill_org', '0060_rename_wrapped_data_overallwrappeddata_extra_data_and_more')]

    dependencies = [
        ('itswill_org', '0035_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascii',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='copypastegroup',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ('view_count',)},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('date', 'name')},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_chicken',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_dance',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_dankies',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_etsmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_gasp',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_giggle',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_ksmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_love',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_lul',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_mmylc',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_monka',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_pog',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_pogo',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_pound',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_seven',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_shoop',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_sit',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_sneak',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_sonic',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_spin',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_stsmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_vvkool',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_chicken',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_dance',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_dankies',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_etsmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_gasp',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_giggle',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_ksmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_love',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_lul',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_mmylc',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_monka',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_pog',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_pogo',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_pound',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_seven',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_shoop',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_sit',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_sneak',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_sonic',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_spin',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_stsmg',
            field=StringCountField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_vvkool',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_cinema',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_glorp',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_gludge',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_ijbol',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_joel',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_lift',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_mad',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_nessie',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_sad',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_sludge',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_wlorp',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_cinema',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_glorp',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_gludge',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_ijbol',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_joel',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_lift',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_mad',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_nessie',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_sad',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_sludge',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_wlorp',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_goodboy',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_happi',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_goodboy',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_happi',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_chedda',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_hehe',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_lmao',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_chedda',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_hehe',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_lmao',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='leaderboards',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_cum',
            field=StringCountField(default=0, verbose_name='Number of cum mentions:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024, verbose_name='First message:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_cum',
            field=StringCountField(default=0, verbose_name='Number of cum mentions:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024, verbose_name='First message:'),
        ),
        migrations.AddField(
            model_name='pet',
            name='drop_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='drop_rate_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_drop_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_drop_rate_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_caw',
            field=StringCountField(default=0, verbose_name='CAW:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_caw',
            field=StringCountField(default=0, verbose_name='CAW:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_goose',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_kirb',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_monka2',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_goose',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_kirb',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_monka2',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='twitchuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='last_message',
            field=models.CharField(default='', max_length=1024, verbose_name='Last message:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='last_message',
            field=models.CharField(default='', max_length=1024, verbose_name='Last message:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_ascii',
            field=itswill_org.models.StatField(default=0, verbose_name='ASCIIs sent:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_characters',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Total characters:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_chatters',
            field=itswill_org.models.StatField(default=0, verbose_name='Number of chatters:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clip_views',
            field=itswill_org.models.StatField(default=0, verbose_name='Views on those clips:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clips',
            field=itswill_org.models.StatField(default=0, verbose_name='Clips created:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_messages',
            field=itswill_org.models.StatField(default=0, verbose_name='Messages sent:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_videos',
            field=itswill_org.models.StatField(default=0, verbose_name='Number of videos:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_ascii',
            field=itswill_org.models.StatField(default=0, verbose_name='ASCIIs sent:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_characters',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Total characters:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_chatters',
            field=itswill_org.models.StatField(default=0, verbose_name='Number of chatters:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clip_views',
            field=itswill_org.models.StatField(default=0, verbose_name='Views on those clips:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clips',
            field=itswill_org.models.StatField(default=0, verbose_name='Clips created:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_messages',
            field=itswill_org.models.StatField(default=0, verbose_name='Messages sent:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_videos',
            field=itswill_org.models.StatField(default=0, verbose_name='Number of videos:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_400',
            field=StringCountField(default=0, verbose_name='400k:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_400',
            field=StringCountField(default=0, verbose_name='400k:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_burger',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_goop',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_burger',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_goop',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_bork',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_bork',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_plus1',
            field=StringCountField(default=0, verbose_name='+1:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_plus1',
            field=StringCountField(default=0, verbose_name='+1:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_clip_duration',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip duration:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_clip_duration',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip duration:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_what',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_what',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_first',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_first',
            field=StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_at_bot',
            field=StringCountField(default=0, verbose_name='Replies to itswillChat:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_at_bot',
            field=StringCountField(default=0, verbose_name='Replies to itswillChat:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_yt',
            field=StringCountField(default=0, verbose_name='YouTube links:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_yt',
            field=StringCountField(default=0, verbose_name='YouTube links:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_q',
            field=StringCountField(default=0, verbose_name='???:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_q',
            field=StringCountField(default=0, verbose_name='???:'),
        ),
        migrations.CreateModel(
            name='OverallWrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('extra_data', models.JSONField(default=dict)),
                ('clip_duration', models.CharField(default='0 seconds', max_length=255)),
                ('jackass_count', models.IntegerField(default=0)),
                ('recap', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.overallrecapdata')),
                ('typing_time', models.CharField(default='0 seconds', max_length=255)),
            ],
            options={
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='UserWrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(default=dict)),
                ('overall_wrapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.overallwrappeddata')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser')),
                ('clip_duration', models.CharField(default='0 seconds', max_length=255)),
                ('jackass_count', models.IntegerField(default=0)),
                ('recap', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.userrecapdata')),
                ('typing_time', models.CharField(default='0 seconds', max_length=255)),
            ],
            options={
                'unique_together': {('overall_wrapped', 'twitch_user')},
            },
        ),
    ]
