# Generated by Django 4.2.11 on 2024-08-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0036_alter_ascii_title_alter_copypastegroup_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ('view_count',)},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('date', 'name')},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_chatters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_videos',
            field=models.IntegerField(default=0),
        ),
    ]
