# Generated by Django 4.2.11 on 2024-08-23 05:16

from django.db import migrations
import itswill_org.models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0038_alter_overallrecapdata_count_chicken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_cinema',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_glorp',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_gludge',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_ijbol',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_joel',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_lift',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_mad',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_nessie',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_sad',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_sludge',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_wlorp',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_cinema',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_glorp',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_gludge',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_ijbol',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_joel',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_lift',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_mad',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_nessie',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_sad',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_sludge',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_wlorp',
            field=itswill_org.models.StringCountField(default=0),
        ),
    ]
