# Generated by Django 4.2.11 on 2024-08-24 03:26

from django.db import migrations
import itswill_org.models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0039_overallrecapdata_count_cinema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_goodboy',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_happi',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_goodboy',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_happi',
            field=itswill_org.models.StringCountField(default=0),
        ),
    ]
