# Generated by Django 4.2.11 on 2024-08-24 03:49

from django.db import migrations
import itswill_org.models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0040_overallrecapdata_count_goodboy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_chedda',
            field=itswill_org.models.CountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_hehe',
            field=itswill_org.models.CountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_lmao',
            field=itswill_org.models.CountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_chedda',
            field=itswill_org.models.CountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_hehe',
            field=itswill_org.models.CountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_lmao',
            field=itswill_org.models.CountField(default=0),
        ),
    ]
