# Generated by Django 4.2.11 on 2024-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0041_overallrecapdata_count_chedda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='leaderboards',
            field=models.JSONField(default=models.Value(None, models.JSONField())),
        ),
    ]
