# Generated by Django 4.2.11 on 2024-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0042_overallrecapdata_leaderboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrecapdata',
            name='leaderboards',
            field=models.JSONField(default=dict),
        ),
    ]
