# Generated by Django 4.2.11 on 2024-08-24 05:23

from django.db import migrations, models
import itswill_org.models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0043_alter_overallrecapdata_leaderboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_chatters',
            field=models.IntegerField(default=0, verbose_name='Number of chatters:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clip_views',
            field=models.IntegerField(default=0, verbose_name='Views on those clips:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clips',
            field=models.IntegerField(default=0, verbose_name='Clips created:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_cum',
            field=itswill_org.models.CountField(default=0, verbose_name='Number of cum mentions:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_messages',
            field=models.IntegerField(default=0, verbose_name='Messages sent:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_videos',
            field=models.IntegerField(default=0, verbose_name='Number of videos:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024, verbose_name='First message:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_chatters',
            field=models.IntegerField(default=0, verbose_name='Number of chatters:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clip_views',
            field=models.IntegerField(default=0, verbose_name='Views on those clips:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clips',
            field=models.IntegerField(default=0, verbose_name='Clips created:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_cum',
            field=itswill_org.models.CountField(default=0, verbose_name='Number of cum mentions:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_messages',
            field=models.IntegerField(default=0, verbose_name='Messages sent:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_videos',
            field=models.IntegerField(default=0, verbose_name='Number of videos:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='first_message',
            field=models.CharField(default='', max_length=1024, verbose_name='First message:'),
        ),
    ]
