# Generated by Django 4.2.11 on 2024-08-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0044_alter_overallrecapdata_count_chatters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='drop_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='drop_rate_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_drop_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_drop_rate_known',
            field=models.BooleanField(default=False),
        ),
    ]
