# Generated by Django 5.1.1 on 2024-12-14 01:21

import itswill_org.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0045_pet_drop_rate_pet_drop_rate_known_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_caw',
            field=itswill_org.models.StringCountField(default=0, verbose_name='CAW:'),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_characters',
            field=models.BigIntegerField(default=0, verbose_name='Total characters:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_caw',
            field=itswill_org.models.StringCountField(default=0, verbose_name='CAW:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_characters',
            field=models.BigIntegerField(default=0, verbose_name='Total characters:'),
        ),
    ]
