# Generated by Django 5.1.1 on 2024-12-14 07:22

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0049_overallrecapdata_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_400',
            field=itswill_org.models.StringCountField(default=0, verbose_name='400k:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_400',
            field=itswill_org.models.StringCountField(default=0, verbose_name='400k:'),
        ),
    ]
