# Generated by Django 5.1.1 on 2024-12-14 07:53

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0050_overallrecapdata_count_400_userrecapdata_count_400'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_burger',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_goop',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_burger',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_goop',
            field=itswill_org.models.StringCountField(default=0),
        ),
    ]
