# Generated by Django 5.1.1 on 2024-12-14 08:06

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0051_overallrecapdata_count_burger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_bork',
            field=itswill_org.models.StringCountField(default=0),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_bork',
            field=itswill_org.models.StringCountField(default=0),
        ),
    ]
