# Generated by Django 5.1.1 on 2024-12-15 01:12

import django.db.models.deletion
import itswill_org.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0052_overallrecapdata_count_bork_userrecapdata_count_bork'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_plus1',
            field=itswill_org.models.StringCountField(default=0, verbose_name='+1:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_plus1',
            field=itswill_org.models.StringCountField(default=0, verbose_name='+1:'),
        ),
        migrations.CreateModel(
            name='OverallWrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('wrapped_data', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='UserWrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_data', models.JSONField(default=dict)),
                ('overall_wrapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.overallwrappeddata')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser')),
            ],
            options={
                'unique_together': {('overall_wrapped', 'twitch_user')},
            },
        ),
    ]
