# Generated by Django 5.1.1 on 2024-12-16 05:12

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0053_overallrecapdata_count_plus1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_clip_duration',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip duration:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_clip_duration',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip duration:'),
        ),
    ]
