# Generated by Django 5.1.1 on 2024-12-18 04:11

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0058_overallrecapdata_count_yt_userrecapdata_count_yt'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_q',
            field=itswill_org.models.StringCountField(default=0, verbose_name='???:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_q',
            field=itswill_org.models.StringCountField(default=0, verbose_name='???:'),
        ),
    ]
