# Generated by Django 5.1.1 on 2024-12-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0060_rename_wrapped_data_overallwrappeddata_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallwrappeddata',
            name='recap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.overallrecapdata'),
        ),
        migrations.AlterField(
            model_name='userwrappeddata',
            name='recap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.userrecapdata'),
        ),
    ]
