# Generated by Django 5.1.1 on 2024-12-19 05:32

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0061_alter_overallwrappeddata_recap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallrecapdata',
            name='count_clip_duration',
        ),
        migrations.RemoveField(
            model_name='userrecapdata',
            name='count_clip_duration',
        ),
        migrations.AddField(
            model_name='overallrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip watch time:'),
        ),
        migrations.AddField(
            model_name='userrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.StatField(default=0, verbose_name='Total clip watch time:'),
        ),
    ]
