# Generated by Django 5.1.1 on 2024-12-19 07:11

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0063_rename_clip_duration_overallwrappeddata_clip_watch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Total clip watch time:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Total clip watch time:'),
        ),
    ]
