# Generated by Django 5.1.1 on 2025-01-24 04:04

from django.db import migrations, models
from django.core.paginator import Paginator

def fill_ids(apps, schema_editor):
  # be sure to change it to your app here
  ChatMessage = apps.get_model("itswill_org", "ChatMessage")
  db_alias = schema_editor.connection.alias
  messages = ChatMessage.objects.using(db_alias).all()
  for i, message in enumerate(messages):
    message.id = i + 1
      
  ChatMessage.objects.using(db_alias).bulk_update(messages, ["id"], batch_size = 1000)

class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0066_clip_itswill_org_created_ffe08a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(editable=False, primary_key=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ChatMessage',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(fill_ids),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
