# Generated by Django 5.1.1 on 2025-01-25 05:52

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0067_auto_20250123_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_characters',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Characters typed:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clip_views',
            field=itswill_org.models.StatField(default=0, verbose_name='Clip views:'),
        ),
        migrations.AlterField(
            model_name='overallrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Clip watch time:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_characters',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Characters typed:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clip_views',
            field=itswill_org.models.StatField(default=0, verbose_name='Clip views:'),
        ),
        migrations.AlterField(
            model_name='userrecapdata',
            name='count_clip_watch',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Clip watch time:'),
        ),
    ]
