# Generated by Django 5.1.1 on 2025-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0068_alter_overallrecapdata_count_characters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterboxdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('watched_date', models.DateField()),
                ('film_title', models.CharField(max_length=255)),
                ('film_year', models.IntegerField(null=True)),
                ('member_rating', models.FloatField(null=True)),
                ('movie_id', models.IntegerField()),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('pub_date',),
                'indexes': [models.Index(fields=['pub_date'], name='itswill_org_pub_dat_3dbc00_idx'), models.Index(fields=['watched_date'], name='itswill_org_watched_7cfb81_idx'), models.Index(fields=['member_rating'], name='itswill_org_member__8c8a4a_idx')],
            },
        ),
    ]
