# Generated by Django 5.1.1 on 2025-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0071_twitchemote_chatmessage_emotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchemote',
            name='animated',
            field=models.BooleanField(default=False),
        ),
    ]
