# Generated by Django 5.1.1 on 2025-06-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0072_twitchemote_animated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchemote',
            name='animated',
        ),
    ]
