# Generated by Django 5.1.1 on 2025-07-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0073_remove_twitchemote_animated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(default='', max_length=512)),
                ('emote', models.CharField(default='', max_length=512)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.fragmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='FragmentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.fragment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.chatmessage')),
            ],
        ),
    ]
