# Generated by Django 5.1.1 on 2025-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0074_fragmentgroup_fragment_fragmentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentgroup',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
