# Generated by Django 5.1.1 on 2025-07-20 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0075_fragmentgroup_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragmentgroup',
            options={'ordering': ('ordering',)},
        ),
        migrations.AlterModelOptions(
            name='fragmentmatch',
            options={'ordering': ('timestamp', 'count')},
        ),
        migrations.AddField(
            model_name='fragmentmatch',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='fragmentmatch',
            unique_together={('fragment', 'message')},
        ),
        migrations.AddIndex(
            model_name='fragmentmatch',
            index=models.Index(fields=['timestamp'], name='itswill_org_timesta_c2a6be_idx'),
        ),
    ]
