# Generated by Django 5.1.1 on 2025-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0076_alter_fragmentgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentgroup',
            name='group_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragmentgroup',
            name='show_in_recap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fragmentgroup',
            name='show_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fragmentgroup',
            name='use_images',
            field=models.BooleanField(default=True),
        ),
    ]
