# Generated by Django 5.1.1 on 2025-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0077_fragmentgroup_group_id_fragmentgroup_show_in_recap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentmatch',
            name='commenter_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddIndex(
            model_name='fragmentmatch',
            index=models.Index(fields=['commenter_id'], name='itswill_org_comment_a24bbb_idx'),
        ),
    ]
