# Generated by Django 5.1.1 on 2025-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0078_fragmentmatch_commenter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentgroup',
            name='count_multiples',
            field=models.BooleanField(default=True),
        ),
    ]
