# Generated by Django 5.1.1 on 2025-07-21 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0079_fragmentgroup_count_multiples'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc), verbose_name='logged at'),
        ),
    ]
