# Generated by Django 5.1.1 on 2025-07-21 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0080_chatmessage_logged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='logged at'),
        ),
    ]
