# Generated by Django 5.1.1 on 2025-07-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0082_remove_overallrecapdata_count_400_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='pretty_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
