# Generated by Django 5.1.1 on 2025-07-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0083_fragment_pretty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='match',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='pretty_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='fragment',
            unique_together={('group', 'pretty_name')},
        ),
    ]
