# Generated by Django 5.2.4 on 2025-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0084_alter_fragment_match_alter_fragment_pretty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
