# Generated by Django 5.2.4 on 2025-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0085_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['commenter'], name='itswill_org_comment_f1f5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['logged_at'], name='itswill_org_logged__0d5a10_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_id'], name='itswill_org_message_ded9dd_idx'),
        ),
    ]
