# Generated by Django 5.2.4 on 2025-07-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0087_fragment_case_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='emote',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
