# Generated by Django 5.2.4 on 2025-07-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0088_alter_fragment_emote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentgroup',
            name='expandable',
            field=models.BooleanField(default=True),
        ),
    ]
