# Generated by Django 5.2.4 on 2025-07-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0089_fragmentgroup_expandable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='emote',
        ),
        migrations.AddField(
            model_name='fragment',
            name='image',
            field=models.FileField(blank=True, upload_to='fragments/'),
        ),
    ]
