# Generated by Django 5.2.5 on 2025-11-15 22:06

import django.db.models.deletion
import itswill_org.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0090_remove_fragment_emote_fragment_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecapdata',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='overallwrappeddata',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='userwrappeddata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrecapdata',
            name='overall_recap',
        ),
        migrations.RemoveField(
            model_name='overallwrappeddata',
            name='recap',
        ),
        migrations.RemoveField(
            model_name='userwrappeddata',
            name='overall_wrapped',
        ),
        migrations.RemoveField(
            model_name='userrecapdata',
            name='twitch_user',
        ),
        migrations.RemoveField(
            model_name='userwrappeddata',
            name='recap',
        ),
        migrations.RemoveField(
            model_name='userwrappeddata',
            name='twitch_user',
        ),
        migrations.CreateModel(
            name='RecapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('month', models.IntegerField(default=1)),
                ('count_messages', itswill_org.models.StatField(default=0, verbose_name='Messages sent:')),
                ('count_characters', itswill_org.models.BigStatField(default=0, verbose_name='Characters typed:')),
                ('count_clips', itswill_org.models.StatField(default=0, verbose_name='Clips created:')),
                ('count_clip_watch', itswill_org.models.BigStatField(default=0, verbose_name='Clip watch time:')),
                ('count_clip_views', itswill_org.models.StatField(default=0, verbose_name='Clip views:')),
                ('count_chatters', itswill_org.models.StatField(default=0, verbose_name='Number of chatters:')),
                ('count_videos', itswill_org.models.StatField(default=0, verbose_name='Number of videos:')),
                ('first_message', models.CharField(default='', max_length=1024, verbose_name='First message:')),
                ('last_message', models.CharField(default='', max_length=1024, verbose_name='Last message:')),
                ('twitch_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser')),
            ],
        ),
        migrations.CreateModel(
            name='FragmentGroupCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('month', models.IntegerField(default=0)),
                ('count', models.BigIntegerField(default=0)),
                ('fragment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.fragmentgroup')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.recapdata')),
            ],
        ),
        migrations.CreateModel(
            name='FragmentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1971)),
                ('month', models.IntegerField(default=0)),
                ('count', models.BigIntegerField(default=0)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.fragment')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.recapdata')),
            ],
        ),
        migrations.CreateModel(
            name='WrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_time', models.CharField(default='0 seconds', max_length=255)),
                ('clip_watch_time', models.CharField(default='0 seconds', max_length=255)),
                ('jackass_count', models.IntegerField(default=0)),
                ('extra_data', models.JSONField(default=dict)),
                ('recap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.recapdata')),
            ],
        ),
        migrations.DeleteModel(
            name='OverallRecapData',
        ),
        migrations.DeleteModel(
            name='OverallWrappedData',
        ),
        migrations.DeleteModel(
            name='UserRecapData',
        ),
        migrations.DeleteModel(
            name='UserWrappedData',
        ),
        migrations.AddIndex(
            model_name='recapdata',
            index=models.Index(fields=['year', 'month'], name='itswill_org_year_94b481_idx'),
        ),
        migrations.AddIndex(
            model_name='recapdata',
            index=models.Index(fields=['year', 'month', 'count_messages'], name='itswill_org_year_933461_idx'),
        ),
        migrations.AddIndex(
            model_name='recapdata',
            index=models.Index(fields=['year', 'month', 'count_clips'], name='itswill_org_year_aa4ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='recapdata',
            index=models.Index(fields=['year', 'month', 'count_clip_views'], name='itswill_org_year_3c8c11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recapdata',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='fragmentgroupcounter',
            index=models.Index(fields=['year', 'month', 'fragment_group', 'count'], name='fragmentgroup_leaderboard_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fragmentgroupcounter',
            unique_together={('recap', 'fragment_group')},
        ),
        migrations.AddIndex(
            model_name='fragmentcounter',
            index=models.Index(fields=['year', 'month', 'fragment', 'count'], name='fragment_leaderboard_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fragmentcounter',
            unique_together={('recap', 'fragment')},
        ),
        migrations.AlterUniqueTogether(
            name='wrappeddata',
            unique_together={('recap',)},
        ),
    ]
