# Generated by Django 5.2.5 on 2025-11-16 05:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0091_remove_userrecapdata_overall_recap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentgroupcounter',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeaderboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('leaderboard_data', models.JSONField(default=dict)),
                ('fragment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.fragmentgroup')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.recapdata')),
            ],
        ),
    ]
