# Generated by Django 5.2.5 on 2025-11-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0092_alter_fragmentgroupcounter_year_leaderboardcache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recapdata',
            unique_together={('year', 'month', 'twitch_user')},
        ),
    ]
