# Generated by Django 5.2.5 on 2025-11-16 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0093_alter_recapdata_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fragmentcounter',
            name='fragment_leaderboard_idx',
        ),
        migrations.RemoveIndex(
            model_name='fragmentgroupcounter',
            name='fragmentgroup_leaderboard_idx',
        ),
        migrations.AddField(
            model_name='fragmentcounter',
            name='twitch_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser'),
        ),
        migrations.AddField(
            model_name='fragmentgroupcounter',
            name='twitch_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser'),
        ),
        migrations.AddIndex(
            model_name='fragmentcounter',
            index=models.Index(fields=['twitch_user', 'year', 'month', 'fragment', 'count'], name='fragment_leaderboard_idx'),
        ),
        migrations.AddIndex(
            model_name='fragmentgroupcounter',
            index=models.Index(fields=['twitch_user', 'year', 'month', 'fragment_group', 'count'], name='fragmentgroup_leaderboard_idx'),
        ),
    ]
