# Generated by Django 5.2.5 on 2025-11-16 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0094_remove_fragmentcounter_fragment_leaderboard_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fragmentmatch',
            name='itswill_org_comment_a24bbb_idx',
        ),
        migrations.AddField(
            model_name='fragmentmatch',
            name='recaps',
            field=models.ManyToManyField(to='itswill_org.recapdata'),
        ),
        migrations.AlterField(
            model_name='fragmentmatch',
            name='commenter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itswill_org.twitchuser'),
        ),
    ]
