# Generated by Django 5.2.5 on 2025-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0095_remove_fragmentmatch_itswill_org_comment_a24bbb_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragmentmatch',
            old_name='commenter_id',
            new_name='commenter',
        ),
    ]
