# Generated by Django 5.2.5 on 2025-11-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0096_rename_commenter_id_fragmentmatch_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardcache',
            name='fragment_group',
        ),
    ]
