# Generated by Django 5.2.5 on 2025-11-17 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0097_remove_leaderboardcache_fragment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardcache',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at'),
        ),
        migrations.AddIndex(
            model_name='fragmentgroupcounter',
            index=models.Index(fields=['year', 'month', 'fragment_group'], name='itswill_org_year_67babf_idx'),
        ),
        migrations.AddIndex(
            model_name='fragmentgroupcounter',
            index=models.Index(fields=['-count'], name='itswill_org_count_db74cd_idx'),
        ),
    ]
