# Generated by Django 5.2.5 on 2025-12-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0098_alter_leaderboardcache_created_at_alter_pet_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fragmentgroupcounter',
            index=models.Index(fields=['year', 'month'], name='itswill_org_year_5ba31e_idx'),
        ),
    ]
