# Generated by Django 5.2.5 on 2025-12-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0099_fragmentgroupcounter_itswill_org_year_5ba31e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappeddata',
            name='vip_gambles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wrappeddata',
            name='vip_wins',
            field=models.IntegerField(default=0),
        ),
    ]
