# Generated by Django 5.2.5 on 2025-12-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0100_wrappeddata_vip_gambles_wrappeddata_vip_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recapdata',
            name='first_message',
        ),
        migrations.RemoveField(
            model_name='recapdata',
            name='last_message',
        ),
    ]
