# Generated by Django 5.2.5 on 2025-12-16 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0101_remove_recapdata_first_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recapdata',
            name='first_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_message_set', to='itswill_org.chatmessage'),
        ),
        migrations.AddField(
            model_name='recapdata',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_set', to='itswill_org.chatmessage'),
        ),
    ]
