# Generated by Django 5.2.5 on 2025-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0102_recapdata_first_message_recapdata_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='fragment_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
