# Generated by Django 5.2.5 on 2025-12-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0103_fragment_fragment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fragment',
            unique_together={('group', 'fragment_id')},
        ),
    ]
