# Generated by Django 5.2.5 on 2025-12-30 22:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0106_customreward_alter_prediction_broadcaster_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='prediction_window',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('LOCKED', 'Locked'), ('RESOLVED', 'Resolved')], max_length=255),
        ),
        migrations.CreateModel(
            name='TwitchBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('banned_at', models.DateTimeField()),
                ('duration', models.IntegerField(default=None, null=True)),
                ('permanent', models.BooleanField()),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_ban_set', to='itswill_org.twitchuser')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchUnban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_unban_set', to='itswill_org.twitchuser')),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itswill_org.twitchuser')),
            ],
        ),
    ]
