# Generated by Django 5.2.5 on 2025-12-30 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0107_chatmessage_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchunban',
            old_name='banned_at',
            new_name='unbanned_at',
        ),
    ]
