# Generated by Django 5.2.5 on 2025-12-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0108_rename_banned_at_twitchunban_unbanned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customreward',
            name='global_cooldown_setting_global_cooldown_seconds',
        ),
        migrations.RemoveField(
            model_name='customreward',
            name='global_cooldown_setting_is_enabled',
        ),
        migrations.RemoveField(
            model_name='customreward',
            name='max_per_stream_setting_is_enabled',
        ),
        migrations.RemoveField(
            model_name='customreward',
            name='max_per_stream_setting_max_per_stream',
        ),
        migrations.RemoveField(
            model_name='customreward',
            name='max_per_user_per_stream_setting_is_enabled',
        ),
        migrations.RemoveField(
            model_name='customreward',
            name='max_per_user_per_stream_setting_max_per_stream',
        ),
        migrations.AddField(
            model_name='customreward',
            name='global_cooldown_setting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customreward',
            name='max_per_stream_setting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customreward',
            name='max_per_user_per_stream_setting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customreward',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='default_image',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='image',
            field=models.JSONField(default=None, null=True),
        ),
    ]
