# Generated by Django 5.2.5 on 2025-12-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0109_remove_customreward_global_cooldown_setting_global_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreward',
            name='background_color',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customrewardredemption',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CANCELED', 'Canceled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled')], max_length=64),
        ),
    ]
