# Generated by Django 5.2.5 on 2025-12-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0110_alter_customreward_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreward',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='is_user_input_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='should_redemptions_skip_request_queue',
            field=models.BooleanField(default=False),
        ),
    ]
