# Generated by Django 5.2.5 on 2025-12-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0111_alter_customreward_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreward',
            name='global_cooldown_setting',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='max_per_stream_setting',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customreward',
            name='max_per_user_per_stream_setting',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
