# Generated by Django 5.2.5 on 2026-01-02 18:27

import itswill_org.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itswill_org', '0112_alter_customreward_global_cooldown_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recapdata',
            name='count_points_gambled',
            field=itswill_org.models.BigStatField(default=0, verbose_name='Channel points gambled:'),
        ),
        migrations.AddField(
            model_name='recapdata',
            name='count_predictions',
            field=itswill_org.models.StatField(default=0, verbose_name='Predictions run:'),
        ),
    ]
